version: '3'

tasks:
  run:
    desc: "Run the application"
    cmds:
      - go run .

  build:
    desc: "Build the application"
    cmds:
      - go build -o main .

  check:
    desc: "Run all checks"
    cmds:
      - go vet ./...
      - golangci-lint run ./...

